name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^16.3.2
  lottie: ^2.7.0
  pdf: ^3.10.6
  printing: ^5.11.0
  intl: ^0.19.0  # For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/scan.png
    - assets/images/
    - assets/animations/
